### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by psachin** [ervikrant06/virsh_xml_parser#2]
```
pip install xmlvirshparser 
Collecting xmlvirshparser
  Using cached xmlvirshparser-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3zw7lllh/xmlvirshparser/setup.py", line 6, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3zw7lllh/xmlvirshparser/
```

**Comment by masaki-furuta** [comment]
Look currently working ? (At least on my F25)

[root@localhost-live ~]# pip install xmlvirshparser
Collecting xmlvirshparser
  Downloading xmlvirshparser-0.5.tar.gz
Collecting xmltodict (from xmlvirshparser)
  Downloading xmltodict-0.10.2.tar.gz
Collecting prettytable (from xmlvirshparser)
  Downloading prettytable-0.7.2.zip
Installing collected packages: xmltodict, prettytable, xmlvirshparser
  Running setup.py install for xmltodict ... done
  Running setup.py install for prettytable ... done
  Running setup.py install for xmlvirshparser ... done
Successfully installed prettytable-0.7.2 xmltodict-0.10.2 xmlvirshparser-0.5
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by psachin** [comment]
@masaki-furuta 

Yes it is working. Try `xmlvirshparser` and it should give you empty table
```
$ xmlvirshparser
+------+-----------+---------------+---------------+--------+----------+-----------+---------------+----------+--------------+
| name | domain-id | instance-uuid | instance-name | flavor | image-id | infac-cnt | infac-details | disk-cnt | disk-details |
+------+-----------+---------------+---------------+--------+----------+-----------+---------------+----------+--------------+
```

You can update version on pip to get rid of warning
```
sudo pip install --upgrade pip 
```

**Comment by psachin** [comment]
In version 0.5 'long description' was removed.
